version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/pkg_lifeblood"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/pkg_lifeblood_viewer"
    schedule:
      interval: "weekly"
