#!/usr/bin/env python

import random
import sys
import time

prefix = '''Redshift Command-Line Renderer (version 3.0.39 - API: 3026)
Copyright 2020 Redshift Rendering Technologies

Querying texture cache buget from preferences.xml: 32 GB
Querying cache path from REDSHIFT_CACHEPATH: /some/cache/path
No GPUs were selected in the command line, using all devices

Creating cache path /some/cache/path
    Enforcing shader cache budget...
    Enforcing texture cache budget...
        Collecting files...
        Total size for 0 files 0.00MB (budget 32768.00MB)
        Under budget. Done.
    Creating mesh cache...
    Done

Redshift Initialized
    Version: 3.0.39, Mar  1 2021
    Linux Platform
    Release Build
    Number of CPU HW threads: 16
    CPU speed: 2.49 GHz
    Total system memory: 28.67 GB
    Current working dir: /tmp
redshift_LICENSE=fooooooo
Creating CUDA contexts
    CUDA init ok
    Ordinals: {{ 0 }}
Initializing GPUComputing module (CUDA). Active device 0
    CUDA Driver Version: 11060
    CUDA API Version: 11000
    Device 1/1 : Quadro RTX 4000 
    Compute capability: 7.5
    Num multiprocessors: 36
    PCI busID: 5, deviceID: 0, domainID: 0
    Theoretical memory bandwidth: 416.063995 GB/Sec
    Measured PCIe bandwidth (pinned CPU->GPU): 12.060690 GB/s
    Measured PCIe bandwidth (pinned GPU->CPU): 12.112527 GB/s
    Measured PCIe bandwidth (paged CPU->GPU): 11.120564 GB/s
    Measured PCIe bandwidth (paged GPU->CPU): 9.713826 GB/s
    Estimated GPU->CPU latency (0): 0.006773 ms
    Estimated GPU->CPU latency (1): 0.006759 ms
    Estimated GPU->CPU latency (2): 0.008178 ms
    Estimated GPU->CPU latency (3): 0.007207 ms
    New CUDA context created
    Available memory: 3999.0625 MB out of 7982.4375 MB
Determining peer-to-peer capability (NVLink or PCIe)
    Done
OptiX denoiser init...
    Selecting device
    Selected device Quadro RTX 4000 (ordinal 0)
OptixRT init...
    Load/set programs
    Ok!

Loading Redshift procedural extensions...
    From path: /path/to/procerurals
    Done!
PostFX initialized

Loading: {filename}

=================================================================================================
Rendering frame {frame}...
AMM enabled
=================================================================================================
REDSHIFT_ABORTONLICENSEFAIL=0
License acquired
License for redshift-core 2022.03 (permanent)
      7ms

Preparing ray tracing hierarchy for meshes
    Time to process 0 meshes:   0ms
    Time to process textures: 0.000009 seconds

Preparing materials and shaders
    Time to process all materials and shaders: 0.725583 seconds

Allocating GPU mem...(device 0)
    Done (Allocator size: 3239 MB. CUDA reported free mem before: 3617 MB, after: 377 MB)

Allocating GPU mem for ray tracing hierarchy processing
    Allocating VRAM for device 0 (Quadro RTX 4000)
        Redshift can use up to 3239 MB
        Fixed: 0 MB
        Geo: 2753 MB, Tex: 0 MB, Rays: 484 MB, NRPR: 262144
        Done! ( 23ms). Compute API reported free mem: 377 MB

Ray Tracing Hierarchy Info:
    Max depth: 128. MaxNumLeafPrimitives: 8
    Extents: (-0.500000 -0.500000 -0.500000) - (0.500000 0.500000 0.500000)
    Time to create tree: 8 ms (0 7 0)

Rendering blocks... (resolution: 1280x720, block size: 128, unified minmax: [4,16])
    Allocating VRAM for device 0 (Quadro RTX 4000)
        Redshift can use up to 3239 MB
        Fixed: 0 MB
        Geo: 1 MB, Tex: 0 MB, Rays: 2867 MB, NRPR: 925024
        Done! ( 18ms). Compute API reported free mem: 377 MB

'''


suffix = '''Processing blocks...
    Time to render {blocks} blocks: {time:.1f}s

Rendering time: {time:.1f}s (1 GPU(s) used)

Scene statistics

    General counts
        Proxies:                                       1
        Proxy instances:                               0
        Meshes:                                        1 (1 TriMeshes, 0 HairMeshes)
        Instances:                                     0
        Point cloud points:                            0
        Lights:                                        1
        Volume grids:                                  0 (0 unique)
        Sprite textures:                               0
        In-core textures:                              0

    Geometry
        Unique triangles pre tessellation:            12
        Unique triangles post tessellation:           12
        Unique points:                                 0
        Unique hair strands:                           0
        Unique hair strand segments:                   0
        Total triangles:                              12
        Total points:                                  0
        Total hair strands:                            0
        Total hair strand segments:                    0

    Largest triangle meshes:
                  12 triangles : box_object1

    GPU Memory
        Device  0 geometry PCIe uploads:              96 B  (cachesize:         1.00 MB)
        Device  0 texture PCIe uploads:                0 B  (cachesize:       128.29 KB)
        Matrices (for instances/points):               0 B 
        Rays:                                       2.80 GB
        Sprite textures:                               0 B 
        In-core textures:                              0 B 
        Volume grids:                                  0 B 

    Textures
        Device  0 stream and upload time:              0ms
            File loading time:                     0ms
            File decompression time:               0ms
            Average GPU cache hits:                0%

    GPU Ray Accel. And Geometry Memory Stats (rough)
        Acceleration Structures:                      96 B 
        Main primitive data:                         176 B 
        Extra primitive data:                         96 B 
        Primitive loading time:                         0ms
        Tess/Disp time:                                 0ms

Saving: {out_beauty}
{out_additional}
Shutdown Rendering Sub-Systems...
Shutdown mem management thread...
Freeing GPU mem...(device 0)
    Done (CUDA reported free mem before: 377 MB, after: 3617 MB)
    Shut down ok
PostFX shut down
Shutdown GPU Devices...
    Device 0
    Auxiliary Device 0
    Devices shut down ok
License returned 
    Finished Shutting down Rendering Sub-Systems
'''


rng = random.Random(13666)


def printwait(stuff, wait_scale=1.0):
    time.sleep(rng.uniform(0.05, 0.5)*wait_scale)
    print(stuff)
    time.sleep(rng.uniform(0.05, 0.5)*wait_scale)


def mock_render(rs_file: str, do_crap_myself=False):
    for line in prefix.format(filename=rs_file,
                              frame=rng.randint(1, 12345)).splitlines():
        printwait(line, wait_scale=0.01)

    blocks = rng.randint(4, 128)
    crap_block = rng.randint(0, blocks + 1) if do_crap_myself else None
    for i in range(blocks + 1):
        printwait(f'    Block {i}/{blocks} ({rng.randint(0, 4096)},{rng.randint(0, 4096)}) rendered by GPU 0 in {rng.randint(0, 100000)}ms', wait_scale=0.1)
        if crap_block == i:
            break

    if do_crap_myself:
        print('OhNo!1! Le ErRoR oCcUrEd !1!1!', file=sys.stderr)
        sys.exit(123)  # TODO: check real redshift error messages and codes

    for line in suffix.format(blocks=blocks,
                              time=rng.uniform(0, 1000),
                              out_beauty='/tmp/test/out.1234.exr',
                              out_additional='Saving: /tmp/fofo/with spaces/file.aov.1234.exr\n'
                                             'Saving: /tmp/fofo/with юникод щит/file.aov.1234.exr').splitlines():
        printwait(line, wait_scale=0.01)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(2)

    mock_render(sys.argv[1])
