#!/usr/bin/env python
import os.path
import sys
import re


def main():
    print("i'm ffmpeg!")

    waiting_for_number = False
    waiting_for_input = False
    inmov = None
    start_frame = 1
    for arg in sys.argv[1:]:
        if waiting_for_input:
            inmov = arg
            waiting_for_input = False
        elif waiting_for_number:
            start_frame = int(arg)
            waiting_for_number = False
        elif arg == '-i':
            waiting_for_input = True
        elif arg == '-start_number':
            waiting_for_number = True
    outseq = sys.argv[-1]

    for frame in range(start_frame, start_frame + 7):  # TODO: this hardcoded 7 should always match the ffprobe value
        with open(re.sub(r"%(0)?(\d+)d", lambda m: '{{:{}{}d}}'.format(m.group(1), m.group(2)).format(frame), outseq), 'w') as f:
            f.write(f'boo {frame}')


if __name__ == '__main__':
    main()
