#!/usr/bin/env python
import sys
import os
import re


def main():
    """
    TODO: add some arg validation, it's too blunt now
    """
    filename = sys.argv[-1]

    print('\n'.join(
        re.match(r'.*?(\d+(?:-\d+)?)\..+', os.path.basename(filename)).group(1).split('-')
    ))


if __name__ == '__main__':
    main()
