name: "release additional tools"

on:
  push:
    paths:
      - dcc_plugins*/**
      - src/lifeblood_client/**
    branches:
      - dev
      - master

jobs:
  build_all_tools:
    uses: ./.github/workflows/build-tools.yml

  make_tool_release:
    needs:
      - build_all_tools
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.derive_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0  # to fetch all history, not just a single commit
      - id: derive_tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Tools auto tag"
          git checkout ${{ github.sha }}
          git tag
          git branch --all
          git log -n5
          
          TAG="$(git describe)-tools"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          
          echo "new tag is $TAG"
          
          git tag -a $TAG -m 'tools autobuild update'
          git push origin $TAG
        working-directory: ./repo
      - uses: actions/download-artifact@v4
        with:
          path:
            tools
      - run: |
          ls -alR tools
          echo tag would be $TAG
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files:
            tools/*/*

  notify:
    uses: ./.github/workflows/release-notify.yml
    secrets:
      TELEGRAM_INFO_BOT_ID: ${{ secrets.TELEGRAM_INFO_BOT_ID }}
      TELEGRAM_INFO_CHANNEL_ID: ${{ secrets.TELEGRAM_INFO_CHANNEL_ID }}
    with:
      message_prepend: "🔧 dcc plugins autoupdate ${{ needs.make_tool_release.outputs.tag }}!\n"
      message_append: |-
        https://github.com/${{ github.repository}}/releases/tag/${{ needs.make_tool_release.outputs.tag }}

        #tools

    needs: [ "make_tool_release" ]