name: "build additional tools"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_houdini_tools:
    runs-on: ubuntu-latest
    container: aaronsmithtv/hbuild:latest
    steps:
      - name: "install dependencies"
        run: |
          apt install -y zip rsync bash
      - uses: actions/checkout@v3
      - run: |
          export PATH=/opt/houdini/build:$PATH
          dcc_plugins_workspace/build_houdini.sh
      - run: |
          ls -alhR dcc_plugins
