name: lint

on:
  push:

jobs:
#  pylint:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.10'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pylint
#    - name: Analysing the code with pylint
#      run: |
#        pylint `ls -R|grep .py$|xargs`

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Analysing the code with flake8
        run: |
          flake8 ./src --count --exit-zero --max-complexity=10 --max-line-length=256 --statistics --format='::warning file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s'
