name: "Documentation"

on:
  push:
    branches: [ dev, master ]
    paths: [ docs/** ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Sphinx Pages
      uses: pedohorse/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        source_dir: docs/source
        install_extensions: true
        create_nojekyll: true
