name: "Documentation"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Sphinx
      uses: ammaraskar/sphinx-action@e781e9af3e80bfe0ea539e4ea46858d51e027214
      with:
        docs-folder: "docs"
        pre-build-command: python -m pip install -r docs/source/requirements.txt

