name: "Tests"

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Sphinx Pages
      uses: seanzhengw/sphinx-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        source_dir: src
